Repository apache/netbeans, pull requests merged in 2019-04, with the labels that each got.

#1183 Update PHP samples
  php/php.samples/samples_src/Calculator-Codeception/composer.json
  php/php.samples/samples_src/Calculator-Codeception/nbproject/project.properties
  php/php.samples/samples_src/Calculator-Codeception/readme.html
  php/php.samples/samples_src/Calculator-Nette-Tester/composer.json
  php/php.samples/samples_src/Calculator-Nette-Tester/nbproject/project.properties
  php/php.samples/samples_src/Calculator-Nette-Tester/readme.html
  php/php.samples/samples_src/Calculator-PHPUnit/composer.json
  php/php.samples/samples_src/Calculator-PHPUnit/nbproject/project.properties
  php/php.samples/samples_src/Calculator-PHPUnit/readme.html
  php/php.samples/samples_src/Calculator-PHPUnit/test/src/CalculatorTest.php
  php/php.samples/samples_src/Calculator-atoum/composer.json
  php/php.samples/samples_src/Calculator-atoum/nbproject/project.properties
  php/php.samples/samples_src/Calculator-atoum/readme.html
  php/php.samples/samples_src/TodoList/layout/index.phtml
  php/php.samples/samples_src/TodoList/nbproject/project.properties
  php/php.samples/samples_src/TodoList/readme.html
Labels: PHP

#1179 NETBEANS-1820 Deleting images with licensing conerns
  webcommon/web.client.samples/EaselDemo/nbproject/project.properties
  webcommon/web.client.samples/EaselDemo/nbproject/project.xml
  webcommon/web.client.samples/EaselDemo/public_html/about.html
  webcommon/web.client.samples/EaselDemo/public_html/css/images/ajax-loader.png
  webcommon/web.client.samples/EaselDemo/public_html/css/images/close_pop.png
  webcommon/web.client.samples/EaselDemo/public_html/css/images/icons-18-black.png
  webcommon/web.client.samples/EaselDemo/public_html/css/images/icons-18-white.png
  webcommon/web.client.samples/EaselDemo/public_html/css/images/icons-36-black.png
  webcommon/web.client.samples/EaselDemo/public_html/css/images/icons-36-white.png
  webcommon/web.client.samples/EaselDemo/public_html/css/style.css
  webcommon/web.client.samples/EaselDemo/public_html/img/cute_rabbit1.jpg
  webcommon/web.client.samples/EaselDemo/public_html/img/cute_rabbit2.jpg
  webcommon/web.client.samples/EaselDemo/public_html/img/cute_rabbit3.jpg
  webcommon/web.client.samples/EaselDemo/public_html/img/glyphicons-halflings-white.png
  webcommon/web.client.samples/EaselDemo/public_html/img/glyphicons-halflings.png
  webcommon/web.client.samples/EaselDemo/public_html/img/kitten1.jpg
  webcommon/web.client.samples/EaselDemo/public_html/img/rabbit1.jpg
  webcommon/web.client.samples/EaselDemo/public_html/img/rabbit2.jpg
  webcommon/web.client.samples/EaselDemo/public_html/img/rabbit3.jpg
  webcommon/web.client.samples/EaselDemo/public_html/index.html
  webcommon/web.client.samples/EaselDemo/public_html/js/about.js
  webcommon/web.client.samples/EaselDemo/public_html/js/draganddrop.js
  webcommon/web.client.samples/EaselDemo/public_html/js/loadWelcome.js
  webcommon/web.client.samples/EaselDemo/public_html/rest/RestClient.js
  webcommon/web.client.samples/EaselDemo/public_html/rest/resources/id19974892.json
  webcommon/web.client.samples/EaselDemo/public_html/rest/resources/id19985678.json
  webcommon/web.client.samples/EaselDemo/public_html/rest/resources/id19986196.json
  webcommon/web.client.samples/EaselDemo/public_html/rest/resources/id19986982.json
  webcommon/web.client.samples/EaselDemo/public_html/rest/resources/manufacturer.json
  webcommon/web.client.samples/EaselDemo/public_html/tableui.html
  webcommon/web.client.samples/build.xml
  webcommon/web.client.samples/licenseinfo.xml
  webcommon/web.client.samples/src/org/netbeans/modules/web/client/samples/layer.xml
  webcommon/web.client.samples/src/org/netbeans/modules/web/client/samples/wizard/ui/Bundle.properties
Labels: Need Cherry Picking

#1181 [NETBEANS-1691] Add support for @supports at-rule (fix error in CSS)
  ide/css.editor/src/org/netbeans/modules/css/editor/csl/CssCompletion.java
  ide/css.lib/manifest.mf
  ide/css.lib/src/org/netbeans/modules/css/lib/Css3.g
  ide/css.lib/src/org/netbeans/modules/css/lib/Css3Lexer.java
  ide/css.lib/src/org/netbeans/modules/css/lib/Css3Parser.java
  ide/css.lib/src/org/netbeans/modules/css/lib/api/CssTokenId.java
  ide/css.lib/src/org/netbeans/modules/css/lib/api/NodeType.java
  ide/css.lib/test/unit/src/org/netbeans/modules/css/lib/Css3LexerTest.java
  ide/css.lib/test/unit/src/org/netbeans/modules/css/lib/Css3ParserTest.java
  ide/css.lib/test/unit/src/org/netbeans/modules/css/lib/api/properties/GrammarResolverListenerTest.java
  ide/css.lib/test/unit/src/org/netbeans/modules/css/lib/api/properties/PropertyValueTest.java
  ide/css.model/src/org/netbeans/modules/css/model/impl/ElementFactoryImpl.java
Labels: CSS

#1205 [NETBEANS-2399] Make sub Project node as a Tree based on the paths on
  groovy/gradle/src/org/netbeans/modules/gradle/nodes/SubProjectsNode.java
Labels: NB11.1

#1217 [NETBEANS-2466] Guard JavaSource.create() result against possible NPE.
  java/java.api.common/src/org/netbeans/modules/java/api/common/project/ActionProviderSupport.java
Labels: NB11.1

#1171 Integration of JEP-330
  java/java.api.common/src/org/netbeans/modules/java/api/common/RunProcess.java
  java/java.api.common/src/org/netbeans/modules/java/api/common/SingleJavaSourceRunActionProvider.java
  java/java.api.common/test/unit/data/files/TestSingleJavaFile.java
  java/java.api.common/test/unit/src/org/netbeans/modules/java/api/common/JavaFileTest.java
  java/java.source/src/org/netbeans/modules/java/Bundle.properties
  java/java.source/src/org/netbeans/modules/java/JavaNode.java
Labels: Need Squashing
