Repository apache/netbeans, pull requests merged in 2019-07, with the labels that each got.

#1334 NP-20 Payara modules improvement
  enterprise/payara.common/manifest.mf
  enterprise/payara.common/nbproject/project.xml
  enterprise/payara.eecommon/nbproject/project.properties
  enterprise/payara.eecommon/nbproject/project.xml
  enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/dd/loader/PayaraDescriptorDataObject.java
  enterprise/payara.jakartaee/manifest.mf
  enterprise/payara.jakartaee/nbproject/project.xml
  enterprise/payara.jakartaee/src/org/netbeans/modules/payara/jakartaee/Hk2JavaEEPlatformImpl.java
  enterprise/payara.jakartaee/src/org/netbeans/modules/payara/jakartaee/Hk2JaxWsStack.java
  enterprise/payara.micro/manifest.mf
  enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/layer.xml
  enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/BaseWizardIterator.java
  enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/MicroProjectWizardIterator.java
  enterprise/payara.tooling/manifest.mf
Labels: NB11.1

#1323 [NETBEANS-2745]:Fixed Convert Switch to Switch-Expression hint for default case without break
  java/java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
  java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertSwitchToRuleSwitchTest.java
Labels: Java, NB11.1, bug

#1337 [NETBEANS-2764] NoClassDefFoundError: com/oracle/truffle/api/library/Library
  webcommon/libs.graaljs/nbproject/project.xml
  webcommon/libs.graaljs/test/unit/src/org/netbeans/libs/graaljs/GraalJSTest.java
  webcommon/libs.truffleapi/manifest.mf
  webcommon/libs.truffleapi/nbproject/project.xml
Labels: NB11.1, bug

#1339 [NETBEANS-2762]: Ensure that if any Java code template parameters nee…
  java/java.editor/src/org/netbeans/modules/editor/java/JavaCodeTemplateProcessor.java
  java/java.editor/test/unit/src/org/netbeans/modules/editor/java/JavaCodeTemplateProcessorTest.java
Labels: NB11.1

#1340 [NETBEANS-2753] Fixed NPE on Java Stacktrace processing.
  groovy/gradle.java/nbproject/project.xml
  groovy/gradle.java/src/org/netbeans/modules/gradle/java/output/JavaCompilerProcessorFactory.java
  groovy/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/output/JavaCompilerProcessorFactoryTest.java
  groovy/gradle/src/org/netbeans/modules/gradle/api/output/OutputListeners.java
  groovy/gradle/src/org/netbeans/modules/gradle/output/GradleProcessorFactory.java
  groovy/gradle/test/unit/src/org/netbeans/modules/gradle/api/output/OutputDisplayerMock.java
  groovy/gradle/test/unit/src/org/netbeans/modules/gradle/output/GradleProcessorFactoryTest.java
Labels: Gradle, NB11.1

#1341 [NETBEANS-2755] Corrected the position of Source for Binary Query for Gradle Repositories.
  groovy/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceForRepository.java
Labels: Gradle, NB11.1

#1343 [NETBEANS-2754] Moved JS Customizer regs. out of Gradle Java EE
  enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/nodes/RestServicesNodeFactory.java
  groovy/gradle.javaee/manifest.mf
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/customizer/GradleCompositePanelProvider.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/layer.xml
  webcommon/html.ojet/src/org/netbeans/modules/html/ojet/ui/OJETFrameworkCustomizer.java
  webcommon/javascript.bower/src/org/netbeans/modules/javascript/bower/ui/libraries/LibraryCustomizer.java
  webcommon/javascript.cdnjs/src/org/netbeans/modules/javascript/cdnjs/CDNJSLibraries.java
  webcommon/javascript.nodejs/src/org/netbeans/modules/javascript/nodejs/ui/libraries/LibraryCustomizer.java
  webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/api/FrameworksUtils.java
  webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/ui/ECMAVersionCustomizer.java
  webcommon/javascript2.requirejs/src/org/netbeans/modules/javascript2/requirejs/ui/RequireJsCustomizer.java
  webcommon/web.clientproject.api/src/org/netbeans/modules/web/clientproject/ui/customizer/JsLibsCompositeCategoryProvider.java
Labels: Gradle, NB11.1

#1344 [NETBEANS-2736] Fixed customizing actions with dot in their name.
  groovy/gradle/src/org/netbeans/modules/gradle/actions/ActionMappingPropertyReader.java
  groovy/gradle/test/unit/src/org/netbeans/modules/gradle/actions/ActionMappingPropertyReaderTest.java
Labels: Gradle, NB11.1

#1346 [NETBEANS-2782] Let Gradle Web Projects discover Java EE 8
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/GradleJavaEEProjectSettings.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/newproject/ServerSelectionPanelVisual.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/newproject/WebApplicationProjectWizard.java
Labels: Gradle, Java EE/Jakarta EE, NB11.1

#1347 [NETBEANS-2775] New Java Web Application Project Duplicate Servers
  enterprise/cloud.amazon/src/org/netbeans/modules/cloud/amazon/AmazonServerInstanceImplementation.java
  enterprise/cloud.amazon/src/org/netbeans/modules/cloud/amazon/serverplugin/AmazonJ2EEServerInstanceImplementation.java
  enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/devmodules/api/ServerManager.java
  enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/bridge/BridgingServerInstance.java
  enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/AddServerInstanceWizard.java
  enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/Bundle.properties
  enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/ServerChooserPanel.java
  enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/ServerChooserVisual.form
  enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/ServerChooserVisual.java
  ide/server/nbproject/org-netbeans-modules-server.sig
  ide/server/nbproject/project.xml
  ide/server/src/org/netbeans/api/server/ServerInstance.java
  ide/server/src/org/netbeans/modules/server/ui/wizard/AddServerInstanceWizard.java
  ide/server/src/org/netbeans/spi/server/ServerInstanceImplementation.java
  ide/server/test/unit/src/org/netbeans/modules/server/test/MockInstanceImplementation.java
Labels: NB11.1

#1348 add check-for-updates chkbox in install wizard
  nbbuild/installer/engine/src/org/netbeans/installer/wizard/components/panels/netbeans/NbPreInstallSummaryPanel.java
Labels: NB11.1

#1350 [NETBEANS-2727] Update the image of the "Pause I/O Checks" toolbar bu…
  platform/masterfs.ui/src/org/netbeans/modules/masterfs/ui/suspend/pause.png
  platform/masterfs.ui/src/org/netbeans/modules/masterfs/ui/suspend/pause24.png
Labels: NB11.1

#1351 [NETBEANS-2727] New images for Start/Stop Self Profiling of IDE
  platform/core.ui/src/org/netbeans/core/ui/sampler/selfSampler.png
  platform/core.ui/src/org/netbeans/core/ui/sampler/selfSampler24.png
  platform/core.ui/src/org/netbeans/core/ui/sampler/selfSamplerRunning.png
  platform/core.ui/src/org/netbeans/core/ui/sampler/selfSamplerRunning24.png
Labels: NB11.1

#1338 Repairs for NETBEANS-2760 and NETBEANS-2761
  enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/registration/AutomaticRegistration.java
  enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
  enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/ConfigBuilderProvider.java
  enterprise/j2ee.common/src/org/netbeans/modules/j2ee/common/J2eeProjectCapabilities.java
  enterprise/j2ee.core/src/org/netbeans/api/j2ee/core/Profile.java
  enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/layer.xml
  enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ui/wizard/archetype/BaseJ2eeArchetypeProvider.java
  enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ui/wizard/archetype/J2eeArchetypeFactory.java
Labels: Java EE/Jakarta EE, NB11.1

#1285 [NETBEANS-2457]: Provided Error Hint to turn on Preview Features in ant/maven Java projects
  apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/java/hints/errors/EnablePreviewAntProj.java
  apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/resources/layer.xml
  java/maven.hints/src/org/netbeans/modules/maven/hints/errors/Bundle.properties
  java/maven.hints/src/org/netbeans/modules/maven/hints/errors/EnablePreviewMavenProj.java
  java/maven.hints/src/org/netbeans/modules/maven/hints/layer.xml
Labels: NB11.1

#1336 [NETBEANS-2756] Added root project relative license file search.
  groovy/gradle/src/org/netbeans/modules/gradle/TemplateAttrProvider.java
  groovy/gradle/src/org/netbeans/modules/gradle/customizer/Bundle.properties
  groovy/gradle/src/org/netbeans/modules/gradle/customizer/LicenseHeadersPanel.form
  groovy/gradle/src/org/netbeans/modules/gradle/customizer/LicenseHeadersPanel.java
Labels: Gradle, NB11.1

#1325 Fixing an IllegalStateException when trying to remove excess entries …
  java/java.source.base/src/org/netbeans/modules/java/source/parsing/ParameterNameProviderImpl.java
  java/java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/ParameterNameProviderImplTest.java
Labels: NB11.1

#1342 [NETBEANS-1087] Fixed double reset action registration on JShell Toolbar
  java/jshell.support/src/org/netbeans/modules/jshell/editor/ResetAction.java
  java/jshell.support/src/org/netbeans/modules/jshell/resources/layer.xml
Labels: NB11.1

#1352 [NETBEANS-2240] (partial) Switch DeferredComplationFailureHandler to …
  java/java.source.base/src/org/netbeans/modules/java/source/parsing/JavacParser.java
  java/java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/JavacParserTest.java
Labels: NB11.1

#1324 [NETBEANS-2730] try to update to nbm-maven-plugin from Apache + backwar…
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/AccessQueryImpl.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/AddOSGiParamToNbmPluginConfiguration.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/CoSApplicationLateBoundChecker.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/InstallerPanel.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenNbModuleImpl.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenRefactoringProviderImpl.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenWhiteListQueryImpl.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NBMNativeMWI.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmActionGoalProvider.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardIterator.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardPanelVisual.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NetBeansRunParamsIDEChecker.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/OpenBrandingEditorAction.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/PluginBackwardPropertyUtils.java
  apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/PublicPackagesPanel.java
Labels: NB11.1

#1354 Comment out Apache Incubator logo on Start Page.
  nb/welcome/src/org/netbeans/modules/welcome/ui/BottomBar.java
Labels: NB11.1

#1356 Add Payara Micro dependency in j2ee.kit
  enterprise/j2ee.kit/nbproject/project.xml
Labels: NB11.1

#1358 Get OpenJFX samples working in release branch.
  javafx/javafx2.kit/nbproject/project.xml
  javafx/openjfx.samples/nbproject/project.properties
  nbbuild/cluster.properties
Labels: NB11.1

#1359 [NETBEANS-2792] Close IO only when all registered Gradle Action Hook finished.
  groovy/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java
  groovy/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
Labels: NB11.1

#1362 [NETBEANS-2813]:Reverting Hint for enabling preview feature in Ant Jav…
  apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/java/hints/errors/EnablePreviewAntProj.java
  apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/resources/layer.xml
Labels: NB11.1

#1365 [NETBEANS-2794] Fix possible ArrayOutOfBoundException when during refactoring.
  java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/tree/FolderTreeElement.java
Labels: NB11.1

#1361 Sync master to release branch for NB 11.1 voting.
  apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/java/hints/errors/EnablePreviewAntProj.java
  apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/resources/layer.xml
  enterprise/j2ee.dd/licenseinfo.xml
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/application-client_8.xsd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/application_8.xsd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/beans_2_0.xsd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/web-common_4_0.xsd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/web-fragment_4_0.xsd
  enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ui/wizard/archetype/BaseJ2eeArchetypeProvider.java
  enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ui/wizard/archetype/J2eeArchetypeFactory.java
  enterprise/servletjspapi/build.xml
  enterprise/servletjspapi/external/binaries-list
  enterprise/servletjspapi/external/javax.servlet-api-4.0.0-license.txt
  enterprise/servletjspapi/external/javax.servlet-api-4.0.1-license.txt
  groovy/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java
  groovy/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
  java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/tree/FolderTreeElement.java
Labels: NB11.1

#1372 NETBEANS-2824 No Properties dialog showing for Java Application
  enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroApplication.java
Labels: NB11.1

#1368 Let Gradle Frontend Application run on JDK11
  groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/desktop_build.gradle.fmk
  groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/root_build.gradle.fmk
  groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/web_build.gradle.fmk
Labels: NB11.1

#1370 [NETBEANS-2831] Removed accidentally left in CDDL_GPL License headers.
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/api/ui/support/CheckBoxUpdater.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/api/ui/support/ComboBoxUpdater.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/AdditionalWebProvider.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/CssPreprocessorsProblemProvider.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/CssPreprocessorsSupport.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/WebEjbJarImpl.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/WebRecoPrivTemplates.java
Labels: NB11.1, license

#1376 [NETBEANS-2700] Let `ant gen-sigtests-release` pass!
  .travis.yml
  enterprise/libs.elimpl/nbproject/org-netbeans-libs-elimpl.sig
  enterprise/libs.elimpl/nbproject/project.properties
  java/java.api.common/nbproject/org-netbeans-modules-java-api-common.sig
  java/java.api.common/src/org/netbeans/modules/java/api/common/SingleJavaSourceRunActionProvider.java
Labels: NB11.1

#1369 [NETBEANS-2343]: Only use the LSP HyperlinkProvider for files that ar…
  ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/HyperlinkProviderImpl.java
  ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java
Labels: NB11.1

#1375 [NETBEANS-2800] - Repairs for Unable to create Servlet/Filter in Java EE 8 application
  enterprise/j2ee.dd/.gitignore
  enterprise/j2ee.dd/build.xml
  enterprise/j2ee.dd/licenseinfo.xml
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/common/DDUtils.java
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/application_8.mdd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/web-app_4_0.mdd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/web-fragment_4_0.mdd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/web/WebAppProxy.java
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/web/WebParseUtils.java
  enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/catalog/EnterpriseCatalog.java
Labels: NB11.1

#1374 Sync master to release branch for NB 11.1-beta4
  .travis.yml
  enterprise/j2ee.dd/.gitignore
  enterprise/j2ee.dd/build.xml
  enterprise/j2ee.dd/licenseinfo.xml
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/common/DDUtils.java
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/application_8.mdd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/web-app_4_0.mdd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/web-fragment_4_0.mdd
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/web/WebAppProxy.java
  enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/web/WebParseUtils.java
  enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/catalog/EnterpriseCatalog.java
  enterprise/libs.elimpl/nbproject/org-netbeans-libs-elimpl.sig
  enterprise/libs.elimpl/nbproject/project.properties
  enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroApplication.java
  groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/desktop_build.gradle.fmk
  groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/root_build.gradle.fmk
  groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/web_build.gradle.fmk
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/api/ui/support/CheckBoxUpdater.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/api/ui/support/ComboBoxUpdater.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/AdditionalWebProvider.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/CssPreprocessorsProblemProvider.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/CssPreprocessorsSupport.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/WebEjbJarImpl.java
  groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/WebRecoPrivTemplates.java
  ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/HyperlinkProviderImpl.java
  ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java
  java/java.api.common/nbproject/org-netbeans-modules-java-api-common.sig
  java/java.api.common/src/org/netbeans/modules/java/api/common/SingleJavaSourceRunActionProvider.java
  nbbuild/notice-stub.txt
Labels: NB11.1, do not merge

#1384 [NETBEANS-1696] PHP 7.4 Support Arrow Functions 2.0
  php/php.editor/src/org/netbeans/modules/php/editor/verification/ImmutableVariablesHint.java
  php/php.editor/src/org/netbeans/modules/php/editor/verification/UninitializedVariableHint.java
  php/php.editor/test/unit/data/testfiles/verification/ImmutableVariablesHint/testImmutableVariablesHint.php
  php/php.editor/test/unit/data/testfiles/verification/ImmutableVariablesHint/testImmutableVariablesHint.php.testWith1AllowedAssignments.hints
  php/php.editor/test/unit/data/testfiles/verification/ImmutableVariablesHint/testImmutableVariablesHintArrowFunctions.php
  php/php.editor/test/unit/data/testfiles/verification/ImmutableVariablesHint/testImmutableVariablesHintArrowFunctions.php.testArrowFunctionsWith1AllowedAssignments.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testArrowFunctions.php
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testArrowFunctions.php.testArrowFunctions.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testGlobalContext.php
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testGlobalContext.php.testGlobalContext.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue225818.php
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue225818.php.testIssue225818.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue226041.php
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue226041.php.testIssue226041.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue233268.php
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue233268.php.testIssue233268.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue246125.php
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue246125.php.testIssue246125.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue249508.php
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue249508.php.testIssue249508.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue257454.php
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testIssue257454.php.testIssue257454.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testUninitializedVariableHint.php
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testUninitializedVariableHint.php.testWithRefs.hints
  php/php.editor/test/unit/data/testfiles/verification/UninitializedVariableHint/testUninitializedVariableHint.php.testWithoutRefs.hints
  php/php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/ImmutableVariablesHintTest.java
  php/php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/UninitializedVariableHintTest.java
Labels: PHP

#1321 Fix SAXEntityParserTest test class in api.xml module
  .travis.yml
  ide/api.xml/test/unit/src/org/netbeans/api/xml/parsers/SAXEntityParserTest.java
Labels: NB11.2

#1364 @deprecation in the comment section , without an @Deprecation annotat…
  enterprise/api.web.webmodule/src/org/netbeans/modules/web/api/webmodule/WebModule.java
  enterprise/api.web.webmodule/src/org/netbeans/modules/web/spi/webmodule/WebModuleFactory.java
  enterprise/api.web.webmodule/src/org/netbeans/modules/web/spi/webmodule/WebModuleImplementation.java
  enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ui/IpComboBox.java
  enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ui/JavaPlatformsComboBox.java
  enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/logging/Logger.java
  enterprise/payara.common/src/org/netbeans/modules/payara/common/ui/IpComboBox.java
  enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/logging/Logger.java
  harness/jellytools.platform/src/org/netbeans/jellytools/actions/Action.java
  harness/jellytools.platform/src/org/netbeans/jellytools/actions/ActionNoBlock.java
  harness/jellytools.platform/src/org/netbeans/jellytools/actions/SaveAction.java
  ide/css.lib/src/org/netbeans/modules/css/lib/api/properties/UnitGrammarElement.java
  ide/css.model/src/org/netbeans/modules/css/live/LiveUpdater.java
  ide/editor.deprecated.pre65formatting/src/org/netbeans/editor/Formatter.java
  ide/editor.deprecated.pre65formatting/src/org/netbeans/editor/ext/ExtFormatter.java
  ide/editor.fold.nbui/src/org/netbeans/modules/editor/fold/ui/CodeFoldingSideBar.java
  ide/html.parser/src/org/netbeans/modules/html/parser/Html5Model.java
  ide/html.parser/src/org/netbeans/modules/html/parser/Html5Parser.java
  ide/image/src/org/netbeans/modules/image/ImageDataObject.java
  ide/jellytools.ide/src/org/netbeans/jellytools/EditorWindowOperator.java
  ide/lib.terminalemulator/src/org/netbeans/lib/terminalemulator/Term.java
  ide/o.openidex.util/src/org/openidex/search/SearchHistory.java
  ide/xml.multiview/src/org/netbeans/modules/xml/multiview/ui/SectionInnerPanel.java
  ide/xml.multiview/src/org/netbeans/modules/xml/multiview/ui/SimpleDialogPanel.java
  ide/xml/src/org/netbeans/modules/xml/actions/CheckEntityAction.java
  java/jellytools.java/src/org/netbeans/jellytools/modules/form/actions/InspectorAction.java
  php/php.api.templates/src/org/netbeans/modules/php/spi/templates/completion/VariableCompletionProvider.java
  platform/api.progress.nb/src/org/netbeans/api/progress/ProgressHandleFactory.java
  platform/api.progress.nb/src/org/netbeans/api/progress/ProgressUtils.java
  platform/autoupdate.services/src/org/netbeans/api/autoupdate/InstallSupport.java
  platform/masterfs.ui/src/org/netbeans/modules/masterfs/providers/AnnotationProvider.java
  platform/openide.awt/src/org/openide/awt/Actions.java
  platform/openide.compat/src/org/openide/explorer/ExplorerActions.java
  platform/openide.compat/src/org/openide/explorer/ExplorerPanel.java
  platform/openide.compat/src/org/openide/util/HttpServer.java
  platform/openide.compat/src/org/openide/util/WeakListener.java
  platform/openide.filesystems/src/org/openide/filesystems/XMLFileSystem.java
  platform/openide.options/src/org/openide/explorer/propertysheet/PropertySheetSettings.java
  platform/openide.options/src/org/openide/options/ContextSystemOption.java
  platform/openide.options/src/org/openide/options/SystemOption.java
  platform/openide.options/src/org/openide/text/PrintSettings.java
  platform/openide.util.ui/src/org/openide/util/NetworkSettings.java
Labels: NB11.2

#1328 HashMap is not thread safe. Field map is typically synchronized by this. However, in two places, field map is not protected with synchronized.
  platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java
Labels: NB11.2

#1335 [NETBEANS-2667] Manage JOptionPane border
  platform/core.windows/src/org/netbeans/core/windows/services/NbPresenter.java
Labels: Need Squashing

#1367 [NETBEANS-2783] Fix missing dependencies nodes in Project view when editing POM file
  java/maven/src/org/netbeans/modules/maven/nodes/DependenciesNode.java
Labels: NB11.2

#1329 [NETBEANS-2729] Make netbeans and netbeans-dev snap descriptor coexists.
  .gitignore
  nbbuild/packaging/netbeans-dev_snap/snap/gui/netbeans.desktop
  nbbuild/packaging/netbeans-dev_snap/snap/snapcraft.yaml
  nbbuild/packaging/netbeans_snap/snap/gui/netbeans.desktop
  nbbuild/packaging/netbeans_snap/snap/snapcraft.yaml
Labels: NB11.2

#1380 Update htmlparser/lexer to support html5 attribute syntax
  ide/html.editor/src/org/netbeans/modules/html/editor/HtmlElementProperties.java
  ide/html.lexer/src/org/netbeans/lib/html/lexer/HtmlLexer.java
  ide/html.lexer/test/unit/src/org/netbeans/lib/html/lexer/HtmlLexerTest.java
  ide/html.parser/external/binaries-list
  ide/html.parser/external/howtoupgrade.txt
  ide/html.parser/external/htmlparser-01-fix-maven-build.patch
  ide/html.parser/external/htmlparser-02-ignore-file.patch
  ide/html.parser/external/htmlparser-03-minimum-changes-nb.patch
  ide/html.parser/external/htmlparser-04-build-on-jdk11.patch
  ide/html.parser/external/htmlparser-1.4.20190624-license.txt
  ide/html.parser/external/htmlparser-howtoupgrade.txt
  ide/html.parser/nbproject/project.properties
  ide/html.parser/nbproject/project.xml
  ide/html.parser/src/org/netbeans/modules/html/parser/Html5Parser.java
  ide/html.parser/src/org/netbeans/modules/html/parser/ParseTreeBuilder.java
  ide/html.parser/src/org/netbeans/modules/html/parser/model/ElementDescriptor.java
  ide/html.parser/test/unit/src/org/netbeans/modules/html/parser/Html5ParserTest.java
  ide/html.parser/test/unit/src/org/netbeans/modules/html/parser/model/HtmlTagProviderTest.java
  nbbuild/licenses/MIT-html5-parser
Labels: NB11.2

#1395 [NETBEANS-2881] Prevent java.lang.StringIndexOutOfBoundsException
  webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/parser/SanitizingParser.java
  webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/parser/JsonParserTest.java
Labels: JavaScript, NB11.2

#1349 [NETBEANS-2785] Move NIO2 File Watcher implementation into the front.
  platform/masterfs.macosx/src/org/netbeans/modules/masterfs/watcher/macosx/OSXNotifier.java
  platform/masterfs.nio2/src/org/netbeans/modules/masterfs/watcher/nio2/NioNotifier.java
  platform/masterfs.windows/src/org/netbeans/modules/masterfs/watcher/windows/WindowsNotifier.java
Labels: NB11.2
