Repository apache/netbeans, pull requests merged in 2019-02, with the labels that each got.

#1110 [NETBEANS-2024] Integrating Git Toolbar
  ide/core.ide/src/org/netbeans/core/ide/resources/Debugging.xml
  ide/core.ide/src/org/netbeans/core/ide/resources/Standard.xml
  ide/git/src/org/netbeans/modules/git/git-layer.xml
Labels: DO NOT squash

#1138 [NETBEANS-2038] Do not dump ambiguous output when a build is cancelled.
  groovy/gradle/src/org/netbeans/modules/gradle/execute/EscapeProcessingOutputStream.java
  groovy/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
Labels: Need Cherry Picking

#1096 Verify 'GraalVM:js' engine is created.
  ide/libs.graalsdk/manifest.mf
  ide/libs.graalsdk/nbproject/project.xml
  nbbuild/travis/scripting.sh
  webcommon/libs.graaljs/nbproject/project.xml
  webcommon/libs.graaljs/test/unit/src/org/netbeans/libs/graaljs/GraalJSTest.java
  webcommon/libs.truffleapi/manifest.mf
  webcommon/libs.truffleapi/nbproject/project.xml
Labels: work-in-progress

#1139 [NETBEANS-2120] Placing synthetically generated classes in spi.java.h…
  java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/JackpotTrees.java
  java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java
Labels: Need Cherry Picking

#1140 [NETBEANS-2121] Updated dependency version on our Java EE support modules.
  groovy/gradle.persistence/nbproject/project.xml
  groovy/gradle.persistence/src/org/netbeans/modules/gradle/persistence/GradlePersistenceProvider.java
  groovy/gradle.persistence/src/org/netbeans/modules/gradle/persistence/PersistenceLocationProviderImpl.java
  groovy/gradle.persistence/src/org/netbeans/modules/gradle/persistence/PersistenceScopeImpl.java
  groovy/gradle.persistence/src/org/netbeans/modules/gradle/persistence/PersistenceScopeProviderImpl.java
Labels: Need Cherry Picking

#1123 Use .class files instead of compiling the sources
  ide/api.java.classpath/apichanges.xml
  ide/api.java.classpath/manifest.mf
  ide/api.java.classpath/src/org/netbeans/api/java/queries/BinaryForSourceQuery.java
  ide/api.java.classpath/src/org/netbeans/modules/java/classpath/QueriesAccessor.java
  ide/api.java.classpath/src/org/netbeans/spi/java/queries/BinaryForSourceQueryImplementation2.java
  ide/api.java.classpath/test/unit/src/org/netbeans/api/java/queries/BinaryForSourceQuery2Test.java
  java/java.source.base/nbproject/project.xml
  java/java.source.base/src/org/netbeans/modules/java/source/indexing/JavaBinaryIndexer.java
  java/java.source.base/src/org/netbeans/modules/java/source/indexing/JavaCustomIndexer.java
  java/java.source.base/src/org/netbeans/modules/java/source/usages/BinaryAnalyser.java
  java/java.source.base/test/unit/src/org/netbeans/api/java/source/SourceUtilsTestUtil.java
  java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/JavaCustomIndexerTest.java
  java/java.source.base/test/unit/src/test2/NoCompileTest.java
  platform/libs.osgi/external/binaries-list
  platform/libs.osgi/external/osgi-7.0-license.txt
  platform/libs.osgi/nbproject/org-netbeans-libs-osgi.sig
  platform/libs.osgi/nbproject/project.properties
  platform/libs.osgi/nbproject/project.xml
Labels: API Change, Need Cherry Picking, enhancement

#1143 [NETBEANS-1995] Exclude extra cluster when generating LICENSE file
  nbbuild/antsrc/org/netbeans/nbbuild/extlibs/CreateLicenseSummary.java
  nbbuild/build.xml
Labels: Need Cherry Picking

#1147 [NETBEANS-2125] Enable Oracle JS Parser to be installed with Java EE
  ergonomics/ide.ergonomics/enterprise.properties
Labels: Need Cherry Picking

#1146 [NETBEANS-2047] Maven/Java project template should be preferred
  java/maven/src/org/netbeans/modules/maven/newproject/idenative/quickstart.html
Labels: Need Cherry Picking

#1141 [NETBEANS-2130] Add support to download/install/register GlassFish 5.1
  enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
  enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
  enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
Labels: Need Cherry Picking

#1048 NETBEANS-1774 Use fragment host instead of fragment bundle for class loading in Netigso
  platform/core.netigso/src/org/netbeans/core/netigso/Netigso.java
  platform/core.netigso/src/org/netbeans/core/netigso/NetigsoLoader.java
  platform/core.netigso/test/unit/src/org/netbeans/core/netigso/NetigsoLoaderOSGiFragmentTest.java
Labels: Need Cherry Picking
